const books =[
    {id:1, name:'Introduciton to Linear algebra',year:'Second_Year',img:'https://drive.google.com/uc?export=view&id=15aJBGXnJGa7_IzcmrebDf9w3Jg1JUH4Q',url:'https://drive.google.com/file/d/1y0JuBXn8Ih_b60z-ikwRXDiynHQMxQAj/view?usp=drive_link'},
    {id:2, name:'Object Oriented Programming in C++',year:'First_Year',img:'https://drive.google.com/uc?export=view&id=1WJm9n_8iI1Bn9a4KltYs-jiXeGvwEw_t',url:'https://drive.google.com/file/d/1Lh_Mb2gmnROWv35NjzvWGL65FJH90lHh/view?usp=drive_link'},
    {id:3, name:'Discrete mathematics and its Applications',year:'First_Year',img:'https://drive.google.com/uc?export=view&id=1bmr4L_dB-zqTGuqT03UDIvJ2g34n9Dv5',url:'https://drive.google.com/file/d/1pmuAsI_2Cu8LVHlPshgYMS2boBRjosGF/view?usp=drive_link'},
    {id:4,name:'Introduction to Java',year:'Second_Year',img:'https://drive.google.com/uc?export=view&id=1srRuatR7iABbCfB3MXjj2ynLSr6uN6i1',url:'https://drive.google.com/file/d/14Xu-iFsGrBODjbXMrMP0s1zh7hl34nF0/view?usp=drive_link'},
    {id:5,name:'Database System Concepts',year:'Second_Year',img:'https://drive.google.com/uc?export=view&id=17YthYeCWsXevbsiScIBCsp6RRF2WolVF',url:'https://drive.google.com/file/d/1qM05TpqaQixMfuY3zxwWSamOJAPATk_Y/view?usp=drive_link'},
    {id:6,name:'Complete IELTS Band 5-6.5',year:'Second_Year',img:'https://drive.google.com/uc?export=view&id=12W_1-yvBO3iNG15i9yOpZDJGvv4b0tjA',url:'https://drive.google.com/file/d/14NsLG8f5fJiKWkBf9oXpNznEJbKhU6oj/view?usp=drive_link'},
    {id:7,name:'English Result Intermediate(Students Edition)',year:'First_Year',img:'https://drive.google.com/uc?export=view&id=1SdCkc3-gcECIh7JnsmYwZQ8T54ECHk20',url:'https://drive.google.com/file/d/1OjwlsroWOt4vMi95LZUAoOmz7rRa_Sar/view?usp=drive_link'},
    {id:6,name:'Software Engineering : A Practitioner Approach',year:'Second_Year',img:'https://drive.google.com/uc?export=view&id=1wEuQlzKb9LFO9IHESOBOZMshM1T4oTTU',url:'https://drive.google.com/file/d/1Vn2vu0FN3WlV0sD_MsmGCXnZUxs15eoS/view?usp=drive_link'},
    {id:7,name:'Thomas Calculus 14th edition',year:'Second_Year',img:'https://drive.google.com/uc?export=view&id=19KakdRHZyZoeQfCmDNp6wNjtRct-iBuA',url:"https://drive.google.com/file/d/1g2NYQIwnEs8NlAHu19QfvcMRHwK52Ybm/view?usp=drive_link"},
    {id:8,name:'Using Information Techonology',year:'First_Year',img:'https://drive.google.com/uc?export=view&id=1S5yRjUmlDkv-6u4EfnGfV5Gia10qc2tY',url:'https://drive.google.com/file/d/1Qn4fWyQhEAwYS38Rr4D6-HhDr_Lluo2X/view?usp=drive_link'},
    {id:9,name:'Data Structure and Algorithms',year:'Second_Year',img:'https://drive.google.com/uc?export=view&id=1ZuVoMIa-UvXCKtGOzH60CXaH3QN0H6rE',url:'https://drive.google.com/file/d/1sGSMyKMjVij-dTnBHnI9g6nOKJAP_4D3/view?usp=drive_link'},
    {id:10,name:'Digital Fundamentals',year:'Second_Year',img:'https://drive.google.com/uc?export=view&id=1Ms4Shu-KEeSXgNRbhyl1AUc-WrfgRZdV',url:'https://drive.google.com/file/d/1O41CEWMZpZJ4JLnW19zlQNj61niUA_1X/view?usp=drive_link'},
    {id:11,name:'Web Development and Design Foundations with HTML 5',year:'First_Year',img:'https://drive.google.com/uc?export=view&id=1hlrT8Qd8QRSSPdigeAHQm8dlBK1pxYRs',url:'https://drive.google.com/file/d/1gA5lZZmcBuFewCNQ8E2l-E8CAxAsrvTu/view?usp=drive_link'},
    {id:12,name:'Programming Logic and Design',year:'First_Year',img:'https://drive.google.com/uc?export=view&id=1ea8n27421yxtznkVz5bsmSgKl4XoezXr',url:'https://drive.google.com/file/d/1jgaBl2FYwGTBHBzcYddHQrvRot-mGldy/view?usp=drive_link'}
]
module.exports={books}